// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpBTokmBRsriODhZnKzWCAiElVZ1gx314',
    appId: '1:881970226415:web:37652623d2979172b7a71a',
    messagingSenderId: '881970226415',
    projectId: 'yorgun-tkm',
    authDomain: 'yorgun-tkm.firebaseapp.com',
    databaseURL: 'https://yorgun-tkm-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'yorgun-tkm.appspot.com',
    measurementId: 'G-TWTH9FHPB3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzblbgU4qxXpbR4brgBgJppYKHxKFjcQ8',
    appId: '1:881970226415:android:a4b181431b8ed363b7a71a',
    messagingSenderId: '881970226415',
    projectId: 'yorgun-tkm',
    databaseURL: 'https://yorgun-tkm-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'yorgun-tkm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIcvDW2_TEoBFILtlWV25zkVsjW1sjMc4',
    appId: '1:881970226415:ios:c76d3b1f9c8873b9b7a71a',
    messagingSenderId: '881970226415',
    projectId: 'yorgun-tkm',
    databaseURL: 'https://yorgun-tkm-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'yorgun-tkm.appspot.com',
    iosClientId: '881970226415-8jh7cacvugm87r4ngpa46o98uqico0r8.apps.googleusercontent.com',
    iosBundleId: 'com.example.yorgun',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIcvDW2_TEoBFILtlWV25zkVsjW1sjMc4',
    appId: '1:881970226415:ios:c76d3b1f9c8873b9b7a71a',
    messagingSenderId: '881970226415',
    projectId: 'yorgun-tkm',
    databaseURL: 'https://yorgun-tkm-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'yorgun-tkm.appspot.com',
    iosClientId: '881970226415-8jh7cacvugm87r4ngpa46o98uqico0r8.apps.googleusercontent.com',
    iosBundleId: 'com.example.yorgun',
  );
}
